#
ENCODER_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = no
VIA_ENABLE = yes

BOOTMAGIC_ENABLE = yes

STENO_ENABLE = yes
STENO_PROTOCOL = txbolt